### ISSUE TITLE
(node:49957) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.TLSSocket instead.

### ISSUE THREAD

**Issue by hktalent** [citronneur/mstsc.js#21]
```
[node-rdpjs] INFO:	screen 1282x332
[node-rdpjs] INFO:	english keyboard layout
[node-rdpjs] INFO:	connect to 192.168.10.124:3389
[node-rdpjs] INFO:	SSL standard security selected
(node:51484) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:51484) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.TLSSocket instead.

```
connect nothing
<img width="484" alt="image" src="https://user-images.githubusercontent.com/18223385/51317865-b45cb500-1a93-11e9-8ff7-451ca94cfdf1.png">
no error
<img width="889" alt="image" src="https://user-images.githubusercontent.com/18223385/51317902-c6d6ee80-1a93-11e9-93ce-a35dbbd65dd4.png">

**Comment by citronneur** [comment]
Hi;

Try another def for your scree. Need to be a power of 2.

**Comment by hktalent** [comment]
@citronneur 
mac os 
```
$node -v
v11.6.0
$ npm -v
6.6.0

$git clone https://github.com/citronneur/mstsc.js.git
$cd mstsc.js
$ node server.js
[node-rdpjs] INFO:	screen 1236x676
[node-rdpjs] INFO:	english keyboard layout
[node-rdpjs] INFO:	connect to 192.168.10.124:3389
[node-rdpjs] INFO:	SSL standard security selected
[node-rdpjs] ERROR:	undefined(crypto.createCredentials is not a function)
TypeError: crypto.createCredentials is not a function
    at BufferLayer.startTLS (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:127:39)
    at Client.recvConnectionConfirm (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:245:28)
    at TPKT.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:202:8)
    at Object.onceWrapper (events.js:276:13)
    at TPKT.emit (events.js:188:13)
    at TPKT.recvData (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:110:7)
    at BufferLayer.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:101:8)
    at Object.onceWrapper (events.js:276:13)
    at BufferLayer.emit (events.js:188:13)
    at BufferLayer.recv (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:92:8)
[node-rdpjs] INFO:	screen 1236x676
[node-rdpjs] INFO:	english keyboard layout
[node-rdpjs] INFO:	connect to 192.168.10.124:3389
[node-rdpjs] INFO:	SSL standard security selected
[node-rdpjs] ERROR:	undefined(crypto.createCredentials is not a function)
TypeError: crypto.createCredentials is not a function
    at BufferLayer.startTLS (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:127:39)
    at Client.recvConnectionConfirm (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:245:28)
    at TPKT.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:202:8)
    at Object.onceWrapper (events.js:276:13)
    at TPKT.emit (events.js:188:13)
    at TPKT.recvData (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:110:7)
    at BufferLayer.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:101:8)
    at Object.onceWrapper (events.js:276:13)
    at BufferLayer.emit (events.js:188:13)
    at BufferLayer.recv (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:92:8)


```

**Comment by hktalent** [comment]
@citronneur 
![image](https://user-images.githubusercontent.com/18223385/51359347-4f8c7380-1b02-11e9-9237-c8d9be7fdc8a.png)
![image](https://user-images.githubusercontent.com/18223385/51359362-603ce980-1b02-11e9-8c9a-d70169486549.png)

```
$npm i -g crypto
$npm i -g node-rdpjs
$ node server.js
[node-rdpjs] INFO:	screen 1236x676
[node-rdpjs] INFO:	english keyboard layout
[node-rdpjs] INFO:	connect to 192.168.10.124:3389
[node-rdpjs] INFO:	SSL standard security selected
[node-rdpjs] ERROR:	undefined(crypto.createCredentials is not a function)
TypeError: crypto.createCredentials is not a function
    at BufferLayer.startTLS (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:127:39)
    at Client.recvConnectionConfirm (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:245:28)
    at TPKT.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:202:8)
    at Object.onceWrapper (events.js:276:13)
    at TPKT.emit (events.js:188:13)
    at TPKT.recvData (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:110:7)
    at BufferLayer.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:101:8)
    at Object.onceWrapper (events.js:276:13)
    at BufferLayer.emit (events.js:188:13)
    at BufferLayer.recv (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:92:8)
[node-rdpjs] INFO:	screen 1236x426
[node-rdpjs] INFO:	english keyboard layout
[node-rdpjs] INFO:	connect to 192.168.10.124:3389
[node-rdpjs] INFO:	SSL standard security selected
[node-rdpjs] ERROR:	undefined(crypto.createCredentials is not a function)
TypeError: crypto.createCredentials is not a function
    at BufferLayer.startTLS (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:127:39)
    at Client.recvConnectionConfirm (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:245:28)
    at TPKT.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/x224.js:202:8)
    at Object.onceWrapper (events.js:276:13)
    at TPKT.emit (events.js:188:13)
    at TPKT.recvData (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:110:7)
    at BufferLayer.<anonymous> (/usr/local/lib/node_modules/node-rdpjs/lib/protocol/tpkt.js:101:8)
    at Object.onceWrapper (events.js:276:13)
    at BufferLayer.emit (events.js:188:13)
    at BufferLayer.recv (/usr/local/lib/node_modules/node-rdpjs/lib/core/layer.js:92:8)

```

**Comment by hktalent** [comment]
```
https://github.com/nodejs/node/blob/ccf37b3a8418e1b086e41dc891ad3575705d76ef/doc/api/deprecations.md
DEP0010: crypto.createCredentials

Type: End-of-Life

The crypto.createCredentials() API was removed. Please use tls.createSecureContext() instead.

```

**Comment by hktalent** [comment]
```
brew uninstall  node
brew install  node@8
echo 'export PATH="/usr/local/opt/node@8/bin:$PATH"' >> ~/.bash_profile
export LDFLAGS="-L/usr/local/opt/node@8/lib"
export CPPFLAGS="-I/usr/local/opt/node@8/include"
source ~/.bash_profile
$node -v
v8.15.0

node server.js
```
node 8,so, ok

**Comment by hktalent** [comment]
please support node 12.4
code is old, run in node 8 is ok
