### ISSUE TITLE
TypeError: crypto.createCredentials is not a function

### ISSUE THREAD

**Issue by Maho91** [citronneur/mstsc.js#31]
Hi there, 
When i am running the project after doing connect I'm getting this error :

TypeError: crypto.createCredentials is not a function
    at BufferLayer.startTLS (D:\rdp\mstsc.js-master\mstsc.js-master\node_modules\node-rdpjs\lib\core\layer.js:127:39)
    at Client.recvConnectionConfirm (D:\rdp\mstsc.js-master\mstsc.js-master\node_modules\node-rdpjs\lib\protocol\x224.js:245:28)
    at TPKT.<anonymous> (D:\rdp\mstsc.js-master\mstsc.js-master\node_modules\node-rdpjs\lib\protocol\x224.js:202:8)
    at Object.onceWrapper (events.js:300:26)
    at TPKT.emit (events.js:210:5)
    at TPKT.recvData (D:\rdp\mstsc.js-master\mstsc.js-master\node_modules\node-rdpjs\lib\protocol\tpkt.js:110:7)
    at BufferLayer.<anonymous> (D:\rdp\mstsc.js-master\mstsc.js-master\node_modules\node-rdpjs\lib\protocol\tpkt.js:101:8)
    at Object.onceWrapper (events.js:300:26)
    at BufferLayer.emit (events.js:210:5)
    at BufferLayer.recv (D:\rdp\mstsc.js-master\mstsc.js-master\node_modules\node-rdpjs\lib\core\layer.js:92:8)

Any help please?

**Comment by Siyer2** [comment]
I'm also facing this issue, did you find a fix?

**Comment by renzo01** [comment]
I have the same problem

**Comment by renzo01** [comment]
it happend , because, the module utf-8 validation si not copilate properly, because node-gyp dosent work

**Comment by Siyer2** [comment]
I found a workaround - [this fork of node-rdpjs](https://github.com/t-system/node-rdpjs) can be added to the package.json. 

Essentially, change 
```
"dependencies": {
		"express": "4.x.x",
		"socket.io": "1.3.x",
		"node-rdpjs": ">=0.2.0"
	},
```
to this. Then `npm install` and `npm start` should do it.
```
"dependencies": {
		"express": "4.x.x",
		"socket.io": "1.3.x",
		"node-rdpjs": "https://github.com/t-system/node-rdpjs.git"
	},
```

**Comment by Vivek-Prajapatii** [comment]
> did it solved the issue?

**Comment by ptallettms** [comment]
I also fixed the issue, but differently - switch to rdpjs@0.3.3
"dependencies": {
		"express": "^4.18.1",
		"rdpjs": "^0.3.3",
		"socket.io": "1.3.x"
	},

/server/mstsc.js line 20
var rdp = require('rdpjs');

Cheers,
Paul

**Comment by lekeshibai** [comment]
> I found a workaround - [this fork of node-rdpjs](https://github.com/t-system/node-rdpjs) can be added to the package.json.
> 
> Essentially, change
> 
> ```
> "dependencies": {
> 		"express": "4.x.x",
> 		"socket.io": "1.3.x",
> 		"node-rdpjs": ">=0.2.0"
> 	},
> ```
> 
> to this. Then `npm install` and `npm start` should do it.
> 
> ```
> "dependencies": {
> 		"express": "4.x.x",
> 		"socket.io": "1.3.x",
> 		"node-rdpjs": "https://github.com/t-system/node-rdpjs.git"
> 	},
> ```
> 
> Note: I didn't write the fork, thanks to t-system!

thank you
