### ISSUE TITLE
NODE_RDP_PROTOCOL_X224_NEG_FAILURE()

### ISSUE THREAD

**Issue by anant-sharma** [citronneur/mstsc.js#7]
@citronneur I am getting the following issue and unable to debug it. Please help me resolve.

```
 [node-rdpjs] INFO:     screen 1366x667
 [node-rdpjs] INFO:     english keyboard layout
 [node-rdpjs] INFO:     connect to 192.168.0.5:3389
 [node-rdpjs] ERROR:    NODE_RDP_PROTOCOL_X224_NEG_FAILURE()
 Error
     at new ProtocolError (/home/anant/mstscjs/node_modules/node-rdpjs/lib/core/error.js:40:8)
     at Client.recvConnectionConfirm (/home/anant/mstscjs/node_modules/node-rdpjs/lib/protocol/x224.js:221:9)
     at TPKT.<anonymous> (/home/anant/mstscjs/node_modules/node-rdpjs/lib/protocol/x224.js:202:8)
     at TPKT.g (events.js:260:16)
     at emitOne (events.js:77:13)
     at TPKT.emit (events.js:169:7)
     at TPKT.recvData (/home/anant/mstscjs/node_modules/node-rdpjs/lib/protocol/tpkt.js:110:7)
     at BufferLayer.<anonymous> (/home/anant/mstscjs/node_modules/node-rdpjs/lib/protocol/tpkt.js:101:8)
     at BufferLayer.g (events.js:260:16)
     at emitOne (events.js:77:13)
```

**Comment by ediweissmann** [comment]
Stumbled upon the same issue. @anant-sharma did you figure out what was the root cause?

**Comment by anant-sharma** [comment]
@ediweissmann - In Remote Desktop settings, Uncheck _Allow connections only from computers running Remote Desktop with Network Level Authentication (recommended)_

**Comment by ediweissmann** [comment]
Thanks

**Comment by citronneur** [comment]
Sorry,

This is because your server use an old version of protocol not supported by this lib.
Thanks.

**Comment by ediweissmann** [comment]
@citronneur Anant's suggestion solved the problem, so I'm guessing `node-rdpjs` doesn't support NLA?

**Comment by lukuilian** [comment]
the same issue. And Anant's suggestion is not work for me.
Any other suggestion???
@citronneur

**Comment by godtang** [comment]
> @ediweissmann - In Remote Desktop settings, Uncheck _Allow connections only from computers running Remote Desktop with Network Level Authentication (recommended)_

The same error is still reported after modification .
What are the requirements for the Windows version of the connection ?

**Comment by chimyking** [comment]
the same issue

**Comment by activeliang** [comment]
the same issue

**Comment by hjzheng** [comment]
the same issue

**Comment by liyang51827** [comment]
@anant-sharma @ediweissmann 
Beside unchecking "Require computers to use Network Level Authentication to connect (recommended)", is there any other solution?

**Comment by MCMathi** [comment]
the same issue

**Comment by ishapkin** [comment]
the same issue
